wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683671865.751261
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.8.16
      5: 0.15.1
      8:
      - 5
model:
  desc: null
  value: /media/ciccio/Sandisk/mosaic-baseline-sav-folder/mosaic-baseline-sav-folder/ur-baseline/1Task-Pick-Place-Mosaic-No-Obj-Detector-Ur5e-Batch128
step:
  desc: null
  value: 40480
task_indx:
  desc: null
  value: 12
results_dir:
  desc: null
  value: /media/ciccio/Sandisk/mosaic-baseline-sav-folder/mosaic-baseline-sav-folder/ur-baseline/1Task-Pick-Place-Mosaic-No-Obj-Detector-Ur5e-Batch128/results_training
num_workers:
  desc: null
  value: 1
project_name:
  desc: null
  value: ur_mosaic_baseline_no_obj_detector_training_rollout
task_name:
  desc: null
  value: pick_place
experiment_number:
  desc: null
  value: 1
debug:
  desc: null
  value: true
training_trj:
  desc: null
  value: true
show_img:
  desc: null
  value: false
run_inference:
  desc: null
  value: false
