#---- Parameters related to env configuration ----#

# Mount type
mount_types: null

# Gripper type
gripper_types: "default"

# Robot offset
# -0.03-(mounting/2)-(table_full_size/2) 
robot_offset: [-0.5305, 0, 0.800] 

# Table dimension
table_full_size: [0.85, 0.85, 0.05]

# Table offset
table_offset: [0, 0, 0.70] # table height

# Object y ranges
y_ranges: [[-0.30, 0.30]]
x_range: [[-0.10, -0.20]]

# Pegs position
peg_positions:
  {
    peg1: [0.125, 0.2, 0.75],
    peg2: [0.125, 0.0, 0.75],
    peg3: [0.125, -0.2, 0.75],
  }

# Camera names
camera_names: ['camera_front','camera_lateral_left','camera_lateral_right','robot0_eye_in_hand'] #,'camera_front', 'camera_lateral_left','camera_lateral_right', 'robot0_eye_in_hand']

#---- CONF 1 ----#
camera_poses:
 # position (x,y,z) and quaternion (w,x,y,z)
  { 
    frontview:  [[0.735, 0, 1.085], [0.5336601734161377, 0.4639042615890503, 0.4639032483100891, 0.5336601734161377]],
    camera_front: [[0.55, 0, 1.085], [0.5693713595118203, 0.4193044895629685, 0.4193044895629685, 0.5693713595118204]], 
    camera_lateral_left: [[-0.33, -0.48, 1.20], [0.9017570913442929, 0.28432292048165225, -0.09790023363307411, -0.31049987013468117]],
    camera_lateral_right: [[-0.33, 0.48, 1.20], [-0.31049987, -0.09790023, 0.28432292, 0.90175709]],
  }

# camera gripper
camera_gripper:
  {
    Robotiq85Gripper: {
                        root: 'right_hand',
                        pose: [[0.0, -0.080, 0.0084], [0.,         0.,         0.97629601, -0.21643961]]
                      },
  }

# camera attributes
camera_attribs:
  {fovy: '60'}

# Camera depth
camera_depths: true

# Camera height
camera_heights: 100

# Camera width
camera_widths: 180

# Horizon
horizon: 1000
ignore_done: False